### ISSUE TITLE
DiscordSRV support

### ISSUE THREAD

**Issue by jakjakob** [NextDevv/AutoMod#4]
currently using this breaks discordSRV, and standing to the [FAQ](https://docs.discordsrv.com/faq#minecraft-chat-to-discord-chat-doesnt-work) with no possibility to fix in config

**Comment by NextDevv** [comment]
Hello, thank you for opening this issue, I'll be implementing DiscordSRV support in the near future. 

Stay up to date on my discord server: https://discord.gg/FcSN67UH9f
